apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    email: tyler180@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-route53
    solvers:
      - dns01:
          route53:
            region: us-west-2
            hostedZoneID: Z04272303NZ93YPTT8MBI
            accessKeyID: AKIASAIR5WMLO7D3C24J
            secretAccessKeySecretRef:
              name: route53-credentials
              key: secret-access-key