apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
    annotations:
        argocd.argoproj.io/sync-wave: "-5"
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:1vjgcd1WccBjp9NfPmNc4WOYzY6+Y8IbwwK6jhSIYNGtzQlT6/8aIrEUxRsDRxjx4Yg=,iv:KyOvTmvdfRy8zzQqb95ZmA4wv8ddJSiyhZuur9Ti1FM=,tag:1sExjcwt0FL4og1hxXzhEw==,type:str]
    postgresql__password: ENC[AES256_GCM,data:vZ9vztCiq1Ui4FLXn43D2O4zjQ5dIbsFiLBg6fnyrQW37r1gWczCRZqfSDfFTqN/FP3biY19GOiD0Du1GSN3aotUHU4FvkcKR6YYdyfm4gg=,iv:gqHHH0AB+8Dpn/Ls2UQSGTQGd/TufqkYEK8059IFOZk=,tag:vZ4X/xmUV3Yuy0qaGL0efg==,type:str]
    email__password: ENC[AES256_GCM,data:zalSvFa68SfZYsQ/aU4MVMxx0LHbZd6LTXYXW7zWhlo8OW8gJMLZpjcJ1BNlhzf5yLI=,iv:Jk10Pf4RcsH+ADXhcEG4AsL/FEbK6UuPjyj980qj/Mo=,tag:zteOBKm7xGRltO/I2TTRLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcy9iQkZWN05LRXdzMGFN
            NFRoSTR1KzlXWERwbStHUHBGd3hDN1hwWm5FCnBrcWx1eXg4cTNiTmx6ektWd3ha
            ZFFhZWYrK1gxejU3Q01GSU5RaUVRSGsKLS0tIGpIRmtMRGhRTWFzOGd6TVhLKzdy
            T1huQ0RpejkvdGF2MVh4ZGtCbHh2YVEKXWxgiSrY6122aC1qdrHrnFq+d3hLNstN
            spTy0EA9LSprTldu6hW5Y65YhwcHNcbLdCamxnR3Lu2oseP20eoSkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10k254sh5xla5q8wqyln94dkajhak2nplgawpjrj0xkuda9c3fd9s08rtm9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T04:01:27Z"
    mac: ENC[AES256_GCM,data:movpnUovL/CMiNfGbJYe/d/Yjs1jj/uXo+UwE9IC44epq1ZuBk/k+oY3ea6xs8bBSG8Tlstq5mj7cL89MNEUksOYEUttClrj/u8S3qz4GbM7kPIgD0ifsyDvEpSDn2YFjRxKRf1WhUO0Z/1NSSNv8CmrZN9isBhALiZIafP8sb0=,iv:x1RwIU/mkq1fAqnbvHt7DN4kpTL6LlCEcW36dMIDtD0=,tag:V6XWJ/IeaZ28lNgcsUignQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql
    namespace: authentik
    annotations:
        argocd.argoproj.io/sync-wave: "-5"
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:yUYLKTKTxYbJeW+67scEbCKjFLvgjKJxAQZ3toyzdfVxbc+kao99Vtw8yKx/gCbzR2SMajAKUhp9N9yPGqiNoVpnOTRsLTDMNwyCTA2vA+8=,iv:KiRtJbS6q0A6rhpXub21cDFFuQmpUh7u+DKwibisaF8=,tag:fIO2Ojboc+21pXRKPikHRA==,type:str]
    postgres-password: ENC[AES256_GCM,data:IvYlTS+VRiix9F0xlFiPEmoDwCtL6jPYOnhOtVpCSwRXQAweRJKV6tKfvZfHw9nihII=,iv:iEI2PHfZ7vLbNyvi2Apy3M0U3aOUqoMuhN0xfXZxgWE=,tag:UP9tGDWTFV0HBFhS1ZLqjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcy9iQkZWN05LRXdzMGFN
            NFRoSTR1KzlXWERwbStHUHBGd3hDN1hwWm5FCnBrcWx1eXg4cTNiTmx6ektWd3ha
            ZFFhZWYrK1gxejU3Q01GSU5RaUVRSGsKLS0tIGpIRmtMRGhRTWFzOGd6TVhLKzdy
            T1huQ0RpejkvdGF2MVh4ZGtCbHh2YVEKXWxgiSrY6122aC1qdrHrnFq+d3hLNstN
            spTy0EA9LSprTldu6hW5Y65YhwcHNcbLdCamxnR3Lu2oseP20eoSkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10k254sh5xla5q8wqyln94dkajhak2nplgawpjrj0xkuda9c3fd9s08rtm9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T04:01:27Z"
    mac: ENC[AES256_GCM,data:movpnUovL/CMiNfGbJYe/d/Yjs1jj/uXo+UwE9IC44epq1ZuBk/k+oY3ea6xs8bBSG8Tlstq5mj7cL89MNEUksOYEUttClrj/u8S3qz4GbM7kPIgD0ifsyDvEpSDn2YFjRxKRf1WhUO0Z/1NSSNv8CmrZN9isBhALiZIafP8sb0=,iv:x1RwIU/mkq1fAqnbvHt7DN4kpTL6LlCEcW36dMIDtD0=,tag:V6XWJ/IeaZ28lNgcsUignQ==,type:str]
    version: 3.13.3
