apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: authentik-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/authentik-secrets.sops.yaml