apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flux-source-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://fluxcd-community.github.io/helm-charts
    chart: source-controller
    targetRevision: v1.9.2
    helm:
      releaseName: source-controller
      values: |
        logLevel: info

  destination:
    server: https://kubernetes.default.svc
    namespace: flux-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true