apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tofu-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/flux-iac/tofu-controller.git
    targetRevision: v0.16.4
    path: config/default

  destination:
    server: https://kubernetes.default.svc
    namespace: flux-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true