apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.20.3
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/infrastructure/cert-manager/values.yaml
    - repoURL: https://github.com/tyler180/homelab-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true