configs:
  cm:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
    url: https://argocd.k8s.749rmw.com
    dex.config: |
      connectors:
        - type: oidc
          id: authentik
          name: authentik
          config:
            issuer: https://auth.k8s.749rmw.com/application/o/argocd/
            clientID: fUE0ft61QUX8F3cnV0mWYeI6sOrEOEWuat3rUc4l
            clientSecret: $argocd-authentik-secret:clientSecret
            insecureEnableGroups: true
            scopes:
              - openid
              - profile
              - email
  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, Argo CD Admins, role:admin
      g, Argo CD Viewers, role:readonly
  params:
    server.insecure: true

repoServer:
  env:
    - name: SOPS_AGE_KEY_FILE
      value: /home/argocd/.config/sops/age/keys.txt
    - name: XDG_CONFIG_HOME
      value: /home/argocd/.config

  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: kustomize-plugins
      emptyDir: {}
    - name: sops-age
      secret:
        secretName: sops-age

  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.5.1
      command:
        - /bin/sh
        - -c
      args:
        - |
          /usr/local/bin/ksops install --with-kustomize /custom-tools
          mkdir -p /plugins/viaduct.ai/v1/ksops
          cp /custom-tools/ksops /plugins/viaduct.ai/v1/ksops/ksops

      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools
        - name: kustomize-plugins
          mountPath: /plugins

  volumeMounts:
    - name: custom-tools
      mountPath: /usr/local/bin/kustomize
      subPath: kustomize
    - name: custom-tools
      mountPath: /usr/local/bin/ksops
      subPath: ksops
    - name: kustomize-plugins
      mountPath: /home/argocd/.config/kustomize/plugin
    - name: sops-age
      mountPath: /home/argocd/.config/sops/age/keys.txt
      subPath: keys.txt
      readOnly: true