apiVersion: v1
kind: Secret
metadata:
    name: sops-test
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:kZWUjLapnBf2,iv:FBXZY5kg7KC1Hzdo/Vj9vQakYtvbxErrnKCQXdvYN4Q=,tag:474yCSsRUSCNVnUfGfV7bQ==,type:str]
    password: ENC[AES256_GCM,data:s2KTZ+BkVc2UdC/ptaiRatTt2Z17,iv:1vJKj0ajZt7mTzHsrYrpngpj5V6tIUetUczAgnsSAn8=,tag:rp3MnACvQs4tWUsl8953SQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQjVUdWNGNTVXYzhjWGov
            VHU2bWdUaXRTVG82aXgvdHBIS3JHNVB1MFVNCmZzRXpVZ2ZXRFNHWmNBcmtpYmNP
            amd1dGxZWUtLbm5acXlGS282OStUZ0EKLS0tIEpDOG5wcXpja251eTdmeGZpalZw
            UkI2Y1Q1QW1EWlFEbXE5VS9CNklHWkUKMEQC3Vp5ILYIiA7URJw0okCC+yhqNqTz
            FfFyVJJjhDyqwnQaPoOftZ5AhRncdxbHzcBPH61Vt6MOqq62xG9/og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10k254sh5xla5q8wqyln94dkajhak2nplgawpjrj0xkuda9c3fd9s08rtm9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T03:08:26Z"
    mac: ENC[AES256_GCM,data:z3KNGRN7XbTPIRMsQXQEPzoo6GC3NVg5MIOFI4OeRbDeer0PLBeM6UeXBzaX/15IbMx/Mq7gjDzG8ZdRbOAYEYlnZyCmqSc3KbYdlQ2Fh+eAcINqh2oJn40HUDyRU6Z6r/ZIpzZfuk+qoUcYcVGLA+MpQJAt/Pa9j/5qzWhpQRE=,iv:QU2Rbm5SQZGxKA2xaCjwYQdgX9tgaw4uWaJUCfK8nHg=,tag:qjSTusdDFE3RzbCZj8f1Lg==,type:str]
    version: 3.13.3
