apiVersion: v1
kind: Secret
metadata:
    name: argocd-authentik-secret
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    clientSecret: v1cOzD7DIMVE4cO4f4xuwVqEK8kQiY7dajBg2UiuiQAV42DzA90qH9wHESf6FeosRETarRfYcMbobAmvpEYW6qutEhrksW3Gdlf4jju4feiFUPl8DlqiPsfgrp1r6x0J
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWE0yMVBDZE1ZMDZoaEJH
            OEpoWEdBdW1lNGU4VWpnbUVUMzBoMm01OTMwCmJRN25MN1lob3h3MEFyVytwQ3Zv
            cW4xZXRQZjVrRDlMcnlKcXJEQnNmelUKLS0tIGhSenJBMEhRSEtyZnBpZm1XY1FF
            QnpEQnFSd0dmSjRtbnNqZEFsRCtSYjgKQr+mRw85fPdahivcW98lsgXz9OkjqnqH
            nhYpe4Re/hs6bxZrvPGJD4G6kHh442IXCO4ki+POWoItkGZ8Q50XYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10k254sh5xla5q8wqyln94dkajhak2nplgawpjrj0xkuda9c3fd9s08rtm9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T07:11:27Z"
    mac: ENC[AES256_GCM,data:r/B35ge6aaXKhXGngNryOMuLF+xJAo1KND9zsJHPoJtA1NLe3s3oi0Y6T4HTxnZoTc9c+bDgu0zd4R60TDULBWezXzEF8JPSqeF3pD+132Qx4+xHohjKRPHwTUXXa2AMGCJ8sX8naAtRjq/gsgSZBftvAXCRT+pyh5xf1hu9xFg=,iv:NuN3ypWWuInS2Kar9Esir3+vc7Py3rUxaVRDt6iuHLE=,tag:r+TNVtHyGa/CBlmGKHMw4g==,type:str]
    version: 3.13.3
