apiVersion: v1
kind: Secret
metadata:
    name: argocd-authentik-secret
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    clientSecret: ENC[AES256_GCM,data:FOfOihOHLlKWsxP9ekFQQJpZDKA+URcl4Qu/D0ct8SXdvSsFUx+vy+JI/CP3YYke+eoENGdcBKjCfCciD1lqULU+YdwGk2r/fFLc2R8gLx7te2Opi2EAP1oCJFUuhbxlXOQfX1yMCLpOXuuMZejJYQl8fUxzbzv5kciEn/Vj/wE=,iv:UFUa9tNwDosTJDSQxzbA0XYi4ajiWoSXhS+B8b46/CY=,tag:2P6u+DH5gh7XLWj3hQmFIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WER0NitsT2IvaktJaXNS
            bklXUFpVenlmbEI0L0FtZU5WTkJ2TmkrR0dzClBlbEJ1WldSUTRObEMySGlLSmd4
            YlkwS0Y1V3loYktRTEk0R3JiRmYzOTgKLS0tIFpQeFVjcnJiZlBmaExqV0RjblY1
            TFluV0dMMVNqUUtrNE9HV2psV3BiclUKH3WkGbyJ6jMOulT2MaK2tf2WBdSrL8dg
            BKKVfaW7zDPQTp2k6fg8LAnH4mrqe0zeZQ2ESbaZe1bZrwFXiN8tUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10k254sh5xla5q8wqyln94dkajhak2nplgawpjrj0xkuda9c3fd9s08rtm9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T15:54:26Z"
    mac: ENC[AES256_GCM,data:b3Y0lRTf9KMyz+VfFvi3m7G3qTfN/2V2Xsa+iamtIy8d2BA92qErYLoRIM4gu7ENcWRgw3rborL0KWay392kbYagz5NTCmUHAVovEJy/usWbUpJykPo6IzOWLkJ+DP00aXFZRBuoijPHCaLs71lbF6uFNdEhRqA3FzpwXvrs7fs=,iv:CAkf4Gr9YGtDfuZPRkCCGitA7OIliEzmwVZZFx9u/p8=,tag:FJsJueUK64Bxfmc6t+nU1A==,type:str]
    version: 3.13.3
