apiVersion: viaduct.ai/v1
kind: ksops-exec
metadata:
  name: argocd-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - argocd-authentik-secret.sops.yaml