global:
  fullnameOverride: authentik

  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-config
          key: secret_key

    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-config
          key: postgresql__password

    - name: AUTHENTIK_EMAIL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-config
          key: email__password

authentik:
  error_reporting:
    enabled: false

  postgresql:
    host: authentik-postgresql
    port: 5432
    name: authentik
    user: authentik

  email:
    host: ""
    port: 587
    username: ""
    from: ""
    use_tls: true
    use_ssl: false

server:
  replicas: 1

  ingress:
    enabled: false

  route:
    main:
      enabled: true
      hostnames:
        - auth.k8s.749rmw.com
      parentRefs:
        - name: public
          namespace: envoy-gateway-system

worker:
  replicas: 1

postgresql:
  enabled: true

  auth:
    username: authentik
    database: authentik
    existingSecret: authentik-postgresql
    secretKeys:
      userPasswordKey: password
      adminPasswordKey: postgres-password

  primary:
    persistence:
      enabled: true
      size: 8Gi